name: {{bot_id}}

services:
  {{bot_id}}:
    build:
      context: .
      dockerfile: ./bots/{{bot_id}}/Dockerfile
    environment:
      PACTO_LOG_LEVEL: ${PACTO_LOG_LEVEL:-info}
      PACTO_TRANSPORT: ${PACTO_TRANSPORT:-unix}
      PACTO_DATA_DIR: ${PACTO_DATA_DIR:-/var/lib/pacto-bot-api}
      PACTO_SECRET_TOKEN: ${PACTO_SECRET_TOKEN:-}
      PACTO_SOCKET_PATH: /run/pacto/pacto-bot-api.sock
    networks:
      - pacto
    volumes:
      - pacto-bot-api-data:/var/lib/pacto-bot-api:ro
    restart: on-failure

networks:
  pacto:
    external: true

volumes:
  pacto-bot-api-data:
    external: true
    name: pacto-bot-api-data

